depth.py - FIXUP missing camx
  File "D:\admin\_private\osgar\osgar\lib\depth.py", line 74, in depth2danger
    [[[params.camx, param.camy, param.camz]]])
AttributeError: 'DepthParams' object has no attribute 'camx'