Patch no longer available CV_LOAD_IMAGE_COLOR on OpenCV3
File "camera_marks.py", line 103, in draw_cnt
  im = cv2.imdecode(buf, cv2.CV_LOAD_IMAGE_COLOR)
AttributeError: module 'cv2.cv2' has no attribute 'CV_LOAD_IMAGE_COLOR'