subt/main.py - fix crash for self.xyz as received list instead of tuple (#634)
File "D:\osgar\subt\main.py", line 581, in update
    self.stdout(timestamp, '(%.1f %.1f %.1f)' % self.xyz if self.xyz is not None else '(xyz=None)', sorted(self.stat.items()))
TypeError: must be real number, not list